### ISSUE TITLE
Normalize em-size for BlackBerry OS6

### ISSUE THREAD

**Issue by vasilisvg** [h5bp/mobile-boilerplate#85]
All browsers in the universe (that I know of) use a default em-size of 16px. The only exception to this rule is BlackBerry OS6 which uses different default font-sizes on different devices. I've seen 22px and even 17px. This causes serious layout issues in em-based layouts on these devices.
The way to solve this is to put the following code into the stylesheet

``` css
:root {
    font-size: 16px;
}
```

This will normalize the base font-size for all current and future browsers. It does remove the ability to adjust the font-size in the browser in IE9 though so you might want to put the code in a somewhat restricting mediaquery:

``` css
@media all and (max-width: 480px) {
    :root {
        font-size: 16px;
    }
}
```
